import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { EquationProvider } from "./contex/EquationContex";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  h-full  antialiased`}
    >
     
      <body className=" bg-linear-to-br from-blue-50 via-purple-50 to-pink-50 min-h-full flex flex-col">
         <EquationProvider>
        <Header />
        {children}
        </EquationProvider>
      </body>
    </html>
  );
}
